import { Component, OnInit } from '@angular/core';
import { FormControl, FormGroup, FormBuilder, Validators } from '@angular/forms';

import { AdmissionType, AssessmentReason, DischargeType, ComatoseState, MemoryState, IndependenceState, 
         HearingAbility, YesNoAnswer, UnderstoodAbility, SpeechClarity, UnderstandingAbility, SeeingAbility,
         IndicatorPresence, MoodPersistence, BehaviouralSymptoms, PerformanceState, HelpRequired, MotionRange,
         ContinenceState, ToiletingPlan, BladderRetrainingProgram, SevenDaysOccurrence, PainFrequency, PainIntensity,
         CalorieCount, CaloriePercent, UlcerNumber, UlcerStage, EvidenceOfProblems, ActivityTime,
         TimeUsed, DischargedTo} from './assessment.constants'

@Component({
  selector: 'assessment',
  templateUrl: './assessment.component.html',
  styleUrls: ['./assessment.component.scss']
})

export class AssessmentComponent {
  
  mdsAssessment: FormGroup;
  admissionType = AdmissionType;
  assessmentReason = AssessmentReason;
  dischargeType = DischargeType;
  comatoseState = ComatoseState;
  memoryState = MemoryState;
  independenceState = IndependenceState;
  hearingAbility = HearingAbility;
  yesnoAnswer = YesNoAnswer;
  understoodAbility = UnderstoodAbility;
  speechClarity = SpeechClarity;
  understandingAbility = UnderstandingAbility;
  seeingAbility = SeeingAbility;
  indicatorPresence = IndicatorPresence;
  moodPersistence = MoodPersistence;
  behaviouralSymptoms = BehaviouralSymptoms;
  performanceState = PerformanceState;
  helpRequired = HelpRequired;
  motionRange = MotionRange;
  continenceState = ContinenceState;
  toiletingPlan = ToiletingPlan;
  bladderretrainingProgram = BladderRetrainingProgram;
  sevendaysOccurrence = SevenDaysOccurrence;
  painFrequency = PainFrequency;
  painIntensity = PainIntensity;
  caloriePercent = CaloriePercent;
  calorieCount = CalorieCount;
  ulcerNumber = UlcerNumber;
  ulcerStage = UlcerStage;
  evidenceofProblems = EvidenceOfProblems;
  activityTime = ActivityTime;
  timeUsed = TimeUsed;
  dischargedTo = DischargedTo;

  constructor(private formBuilder: FormBuilder) {}

  ngOnInit() {
    this.mdsAssessment = this.formBuilder.group({
      Master_No: ['1234', Validators.required],
      Resident_Identifier: '1234567890',
      A3: '20170422',
      AA7: '01',
      AA8: '01', 
      AA9: '--',
      AB1: '20170422',
      AB10a: '-',
      AB10b: '-',
      AB10c: '-',
      AB10d: '-',
      AB10e: '-',
      AB10f: '-',
      AB2a: '-',
      AB2b: '-',
      AB3: '-',
      AB5a: '-',
      AB5b: '-',
      AB5c: '-',
      AB5d: '-',
      AB5e: '-',
      AB7: '-',
      AB8: '-',
      AB9: '-',
      AC1a: '-',
      AC1b: '-',
      AC1c: '-',
      AC1d: '-',
      AC1e: '-',
      AC1f: '-',
      AC1g: '-',
      AC1i: '-',
      AC1j: '-',
      AC1k: '-',
      AC1m: '-',
      AC1n: '-',
      AC1o: '-',
      AC1p: '-',
      AC1q: '-',
      AC1s: '-',
      AC1t: '-',
      AC1u: '-',
      AC1v: '-',
      AC1w: '-',
      AD1: '-',
      AD2: 'OTHR',
      B1: '0',
      B2a: '0',
      B2b: '-',
      B3a: '-',
      B3b: '-',
      B3c: '-',
      B3d: '-',
      B4: '0',
      B5a: '-',
      B5b: '-',
      B5c: '-',
      B5d: '-',
      B5e: '-',
      B5f: '-',
      B6: '-',
      C1: '0',
      C2a: '-',
      C2b: '-',
      C2c: '-',
      C3a: '-',
      C3b: '0',
      C3c: '0',
      C3d: '0',
      C3e: '0',
      C3f: '0',
      C4: '0',
      C5: '0',
      C6: '0',
      C7: '-',
      D1: '0',
      D2a: '0',
      D2b: '0',
      D3: '0',
      E1a: '0',
      E1b: '0',
      E1c: '0',
      E1d: '0',
      E1e: '0',
      E1f: '0',
      E1g: '0',
      E1h: '0',
      E1i: '0',
      E1j: '0',
      E1k: '0',
      E1l: '0',
      E1m: '0',
      E1n: '0',
      E1o: '0',
      E1p: '0',
      E2: '0',
      E3: '-',
      E4aA: '0',
      E4aB: '-',
      E4bA: '0',
      E4bB: '-',
      E4cA: '0',
      E4cB: '-',
      E4dA: '0',
      E4dB: '-',
      E4eA: '0',
      E4eB: '-',
      E5: '-',
      F1a: '-',
      F1b: '-',
      F1c: '-',
      F1d: '-',
      F1e: '-',
      F1f: '-',
      F2a: '-',
      F2b: '-',
      F2c: '-',
      F2d: '-',
      F2e: '-',
      F2f: '-',
      F2g: '-',
      F3a: '-',
      F3b: '-',
      F3c: '-',
      G1aA: '0',
      G1aB: '-',
      G1bA: '0',
      G1bB: '0',
      G1cA: '-',
      G1dA: '-',
      G1dB: '-',
      G1eA: '0',
      G1eB: '-',
      G1fA: '-',
      G1fB: '-',
      G1gA: '0',
      G1gB: '-',
      G1hA: '0',
      G1hB: '-',
      G1iA: '0',
      G1iB: '-',
      G1jA: '-',
      G1jB: '-',
      G2a: '-',
      G2b: '-',
      G3a: '-',
      G3b: '-',
      G4aA: '0',
      G4aB: '-',
      G4bA: '0',
      G4bB: '-',
      G4cA: '0',
      G4cB: '-',
      G4dA: '0',
      G4dB: '-',
      G4eA: '0',
      G4eB: '-',
      G4fA: '0',
      G4fB: '-',
      G5a: '-',
      G5b: '-',
      G5c: '-',
      G5d: '-',
      G6a: '-',
      G6b: '-',
      G6c: '-',
      G6d: '-',
      G6e: '-',
      G7: '-',
      G8a: '-',
      G8b: '-',
      G8c: '-',
      G8d: '-',
      G9: '-',
      H1a: '0',
      H1b: '0',
      H2a: '-',
      H2b: '-',
      H2c: '-',
      H2d: '0',
      H3a: '0',
      H3b: '0',
      H3c: '-',
      H3d: '0',
      H3e: '-',
      H3f: '-',
      H3g: '-',
      H3h: '-',
      H3i: '0',
      H4: '-',
      I1a: '0',
      I1aA: '-',
      I1b: '-',
      I1bB: '-',
      I1c: '-',
      I1cC: '-',
      I1d: '-',
      I1dD: '-',
      I1e: '-',
      I1eE: '-',
      I1f: '-',
      I1fF: '-',
      I1g: '-',
      I1gG: '-',
      I1h: '-',
      I1hH: '-',
      I1i: '-',
      I1iI: '-',
      I1j: '-',
      I1jJ: '-',
      I1k: '-',
      I1kK: '-',
      I1l: '-',
      I1lL: '-',
      I1m: '-',
      I1mM: '-',
      I1n: '-',
      I1nN: '-',
      I1o: '-',
      I1oO: '-',
      I1p: '-',
      I1pP: '-',
      I1q: '-',
      I1qQ: '-',
      I1r: '-',
      I1rR: '-',
      I1s: '0',
      I1sS: '-',
      I1t: '0',
      I1tT: '-',
      I1u: '-',
      I1uU: '-',
      I1v: '-',
      I1w: '0',
      I1x: '-',
      I1z: '-',
      I2a: '-',
      I2b: '-',
      I2c: '-',
      I2d: '-',
      I2e: '-',
      I2f: '0',
      I2g: '0',
      I2h: '0',
      I2i: '-',
      I2j: '-',
      I2k: '0',
      I2l: '-',
      I2m: '-',
      I3a: '-',
      I3b: '-',
      I3c: '-',
      I3d: '-',
      I3e: '-',
      I3f: '-',
      J1a: '-',
      J1b: '-',
      J1c: '0',
      J1d: '-',
      J1e: '0',
      J1f: '-',
      J1g: '-',
      J1h: '0',
      J1i: '0',
      J1j: '0',
      J1k: '-',
      J1l: '-',
      J1m: '-',
      J1n: '-',
      J1o: '0',
      J2a: '0',
      J2b: '--',
      J3a: '-',
      J3b: '-',
      J3c: '-',
      J3d: '-',
      J3e: '-',
      J3f: '-',
      J3g: '-',
      J3h: '-',
      J3i: '-',
      J3j: '-',
      J4a: '0',
      J4b: '-',
      J4c: '0',
      J4d: '0',
      J5a: '-',
      J5b: '-',
      J5c: '0',
      K1a: '-',
      K1b: '-',
      K1c: '-',
      K2a: '-',
      K2b: '-',
      K3a: '0',
      K3b: '-',
      K4a: '-',
      K4b: '-',
      K4c: '-',
      K5a: '0',
      K5b: '0',
      K5c: '-',
      K5d: '-',
      K5e: '-',
      K5f: '-',
      K5g: '-',
      K5h: '0',
      K6a: '0',
      K6b: '--',
      L1a: '-',
      L1b: '-',
      L1c: '0',
      L1d: '0',
      L1e: '0',
      L1f: '-',
      M1a: '0',
      M1b: '0',
      M1c: '0',
      M1d: '0',
      M2a: '0',
      M2b: '-',
      M3: '0',
      M4a: '0',
      M4b: '-',
      M4c: '0',
      M4d: '-',
      M4e: '-',
      M4f: '-',
      M4g: '0',
      M5a: '0',
      M5b: '0',
      M5c: '0',
      M5d: '0',
      M5e: '0',
      M5f: '0',
      M5g: '0',
      M5h: '0',
      M5i: '-',
      M6a: '-',
      M6b: '0',
      M6c: '0',
      M6d: '-',
      M6e: '-',
      M6f: '0',
      N1a: '0',
      N1b: '0',
      N1c: '0',
      N2: '0',
      N3a: '-',
      N3b: '-',
      N3c: '-',
      N3d: '-',
      N4a: '-',
      N4b: '-',
      N4c: '-',
      N4d: '-',
      N4e: '-',
      N4f: '-',
      N4g: '-',
      N4h: '-',
      N4i: '-',
      N4j: '-',
      N4k: '-',
      N4l: '-',
      N5a: '-',
      N5b: '-',
      O1: '-',
      O2: '-',
      O3: '0',
      O4a: '-',
      O4b: '0',
      O4c: '0',
      O4d: '0',
      O4e: '-',
      O4f: '-',
      P1aA: '-',
      P1aB: '-',
      P1aC: '-',
      P1aD: '-',
      P1aE: '-',
      P1aF: '-',
      P1aG: '-',
      P1aH: '-',
      P1aI: '-',
      P1aJ: '-',
      P1aK: '-',
      P1aL: '-',
      P1aM: '-',
      P1aN: '-',
      P1aO: '0',
      P1aP: '-',
      P1aQ: '-',
      P1aR: '-',
      P1baA: '0',
      P1baB: '0',
      P1bbA: '0',
      P1bbB: '0',
      P1bcA: '0',
      P1bcB: '0',
      P1bdA: '0',
      P1bdB: '-',
      P1beA: '-',
      P1beB: '-',
      P1bfA: '-',
      P1bfB: '-',
      P2a: '-',
      P2b: '-',
      P2c: '-',
      P2d: '-',
      P2e: '-',
      P3a: '0',
      P3b: '0',
      P3c: '0',
      P3d: '0',
      P3e: '0',
      P3f: '0',
      P3g: '0',
      P3h: '0',
      P3i: '0',
      P3j: '0',
      P3k: '-',
      P4a: '-',
      P4b: '-',
      P4c: '0',
      P4d: '0',
      P4e: '-',
      P5: '-',
      P6: '-',
      P7: '0',
      P8: '0',
      P9: '-',
      Q1a: '-',
      Q1b: '-',
      Q1c: '-',
      Q2: '-',
      R1a: '-',
      R1b: '-',
      R1c: '-',
      R2b: '-',
      R3a: '0',
      R3b: '-',
      R4: '-',
      Y2: '-',
      Z12: '-',
      IAR_1: '2013',
      Org_ID: '-',
      Assessment_ID: '-'
    })
  }
}