import { Component, OnInit } from '@angular/core';
import { FormControl, FormGroup, FormBuilder, Validators } from '@angular/forms';

import { AdmissionType, AssessmentReason, DischargeType, 
         ComatoseState, MemoryState, IndependenceState, 
         HearingAbility, YesNoAnswer, UnderstoodAbility, 
         SpeechClarity, UnderstandingAbility, SeeingAbility,
         IndicatorPresence, MoodPersistence, BehaviouralSymptoms,
         PerformanceState, HelpRequired, MotionRange,
         ContinenceState, ToiletingPlan, BladderRetrainingProgram,
         SevenDaysOccurrence, PainFrequency, PainIntensity,
         CalorieCount, CaloriePercent, UlcerNumber,
         UlcerStage, EvidenceOfProblems,
} from './assessment.constants'

@Component({
  selector: 'assessment',
  templateUrl: './assessment.component.html',
  styleUrls: ['./assessment.component.scss']
})

export class AssessmentComponent {
  
  mdsAssessment: FormGroup;
  admissionType = AdmissionType;
  assessmentReason = AssessmentReason;
  dischargeType = DischargeType;
  comatoseState = ComatoseState;
  memoryState = MemoryState;
  independenceState = IndependenceState;
  hearingAbility = HearingAbility;
  yesnoAnswer = YesNoAnswer;
  understoodAbility = UnderstoodAbility;
  speechClarity = SpeechClarity;
  understandingAbility = UnderstandingAbility;
  seeingAbility = SeeingAbility;
  indicatorPresence = IndicatorPresence;
  moodPersistence = MoodPersistence;
  behaviouralSymptoms = BehaviouralSymptoms;
  performanceState = PerformanceState;
  helpRequired = HelpRequired;
  motionRange = MotionRange;
  continenceState = ContinenceState;
  toiletingPlan = ToiletingPlan;
  bladderretrainingProgram = BladderRetrainingProgram;
  sevendaysOccurrence = SevenDaysOccurrence;
  painFrequency = PainFrequency;
  painIntensity = PainIntensity;
  caloriePercent = CaloriePercent;
  calorieCount = CalorieCount;
  ulcerNumber = UlcerNumber;
  ulcerStage = UlcerStage;
  evidenceofProblems = EvidenceOfProblems;

  constructor(private formBuilder: FormBuilder) {}

  ngOnInit() {
    this.mdsAssessment = this.formBuilder.group({
      master_no: ['1234', Validators.required],
      resident_identifier: '1234567890',
      a3: '20170422',
      aa7: '01',
      aa8: '01', 
      aa9: '--',
      ab1: '20170422',
      ab10a: '-',
      ab10b: '-',
      ab10c: '-',
      ab10d: '-',
      ab10e: '-',
      ab10f: '-',
      ab2a: '-',
      ab2b: '-',
      ab3: '-',
      ab5a: '-',
      ab5b: '-',
      ab5c: '-',
      ab5d: '-',
      ab5e: '-',
      ab7: '-',
      ab8: '-',
      ab9: '-',
      ac1a: '-',
      ac1b: '-',
      ac1c: '-',
      ac1d: '-',
      ac1e: '-',
      ac1f: '-',
      ac1g: '-',
      ac1i: '-',
      ac1j: '-',
      ac1k: '-',
      ac1m: '-',
      ac1n: '-',
      ac1o: '-',
      ac1p: '-',
      ac1q: '-',
      ac1s: '-',
      ac1t: '-',
      ac1u: '-',
      ac1v: '-',
      ac1w: '-',
      ad1: '-',
      ad2: 'OTHR',
      b1: '0',
      b2a: '0',
      b2b: '-',
      b3a: '-',
      b3b: '-',
      b3c: '-',
      b3d: '-',
      b4: '0',
      b5a: '-',
      b5b: '-',
      b5c: '-',
      b5d: '-',
      b5e: '-',
      b5f: '-',
      b6: '-',
      c1: '0',
      c2a: '-',
      c2b: '-',
      c2c: '-',
      c3a: '-',
      c3b: '0',
      c3c: '0',
      c3d: '0',
      c3e: '0',
      c3f: '0',
      c4: '0',
      c5: '0',
      c6: '0',
      c7: '-',
      d1: '0',
      d2a: '0',
      d2b: '0',
      d3: '0',
      e1a: '0',
      e1b: '0',
      e1c: '0',
      e1d: '0',
      e1e: '0',
      e1f: '0',
      e1g: '0',
      e1h: '0',
      e1i: '0',
      e1j: '0',
      e1k: '0',
      e1l: '0',
      e1m: '0',
      e1n: '0',
      e1o: '0',
      e1p: '0',
      e2: '0',
      e3: '-',
      e4aa: '0',
      e4ab: '-',
      e4ba: '0',
      e4bb: '-',
      e4ca: '0',
      e4cb: '-',
      e4da: '0',
      e4db: '-',
      e4ea: '0',
      e4eb: '-',
      e5: '-',
      f1a: '-',
      f1b: '-',
      f1c: '-',
      f1d: '-',
      f1e: '-',
      f1f: '-',
      f2a: '-',
      f2b: '-',
      f2c: '-',
      f2d: '-',
      f2e: '-',
      f2f: '-',
      f2g: '-',
      f3a: '-',
      f3b: '-',
      f3c: '-',
      g1aa: '0',
      g1ab: '-',
      g1ba: '0',
      g1bb: '0',
      g1ca: '-',
      g1da: '-',
      g1db: '-',
      g1ea: '0',
      g1eb: '-',
      g1fa: '-',
      g1fb: '-',
      g1ga: '0',
      g1gb: '-',
      g1ha: '0',
      g1hb: '-',
      g1ia: '0',
      g1ib: '-',
      g1ja: '-',
      g1jb: '-',
      g2a: '-',
      g2b: '-',
      g3a: '-',
      g3b: '-',
      g4aa: '0',
      g4ab: '-',
      g4ba: '0',
      g4bb: '-',
      g4ca: '0',
      g4cb: '-',
      g4da: '0',
      g4db: '-',
      g4ea: '0',
      g4eb: '-',
      g4fa: '0',
      g4fb: '-',
      g5a: '-',
      g5b: '-',
      g5c: '-',
      g5d: '-',
      g6a: '-',
      g6b: '-',
      g6c: '-',
      g6d: '-',
      g6e: '-',
      g7: '-',
      g8a: '-',
      g8b: '-',
      g8c: '-',
      g8d: '-',
      g9: '-',
      h1a: '0',
      h1b: '0',
      h2a: '-',
      h2b: '-',
      h2c: '-',
      h2d: '0',
      h3a: '0',
      h3b: '0',
      h3c: '-',
      h3d: '0',
      h3e: '-',
      h3f: '-',
      h3g: '-',
      h3h: '-',
      h3i: '0',
      h4: '-',
      i1a: '0',
      i1aa: '-',
      i1b: '-',
      i1bb: '-',
      i1c: '-',
      i1cc: '-',
      i1d: '-',
      i1dd: '-',
      i1e: '-',
      i1ee: '-',
      i1f: '-',
      i1ff: '-',
      i1g: '-',
      i1gg: '-',
      i1h: '-',
      i1hh: '-',
      i1i: '-',
      i1ii: '-',
      i1j: '-',
      i1jj: '-',
      i1k: '-',
      i1kk: '-',
      i1l: '-',
      i1ll: '-',
      i1m: '-',
      i1mm: '-',
      i1n: '-',
      i1nn: '-',
      i1o: '-',
      i1oo: '-',
      i1p: '-',
      i1pp: '-',
      i1q: '-',
      i1qq: '-',
      i1r: '-',
      i1rr: '-',
      i1s: '0',
      i1ss: '-',
      i1t: '0',
      i1tt: '-',
      i1u: '-',
      i1uu: '-',
      i1v: '-',
      i1w: '0',
      i1x: '-',
      i1z: '-',
      i2a: '-',
      i2b: '-',
      i2c: '-',
      i2d: '-',
      i2e: '-',
      i2f: '0',
      i2g: '0',
      i2h: '0',
      i2i: '-',
      i2j: '-',
      i2k: '0',
      i2l: '-',
      i2m: '-',
      i3a: '-',
      i3b: '-',
      i3c: '-',
      i3d: '-',
      i3e: '-',
      i3f: '-',
      j1a: '-',
      j1b: '-',
      j1c: '0',
      j1d: '-',
      j1e: '0',
      j1f: '-',
      j1g: '-',
      j1h: '0',
      j1i: '0',
      j1j: '0',
      j1k: '-',
      j1l: '-',
      j1m: '-',
      j1n: '-',
      j1o: '0',
      j2a: '0',
      j2b: '--',
      j3a: '-',
      j3b: '-',
      j3c: '-',
      j3d: '-',
      j3e: '-',
      j3f: '-',
      j3g: '-',
      j3h: '-',
      j3i: '-',
      j3j: '-',
      j4a: '0',
      j4b: '-',
      j4c: '0',
      j4d: '0',
      j5a: '-',
      j5b: '-',
      j5c: '0',
      k1a: '-',
      k1b: '-',
      k1c: '-',
      k2a: '-',
      k2b: '-',
      k3a: '0',
      k3b: '-',
      k4a: '-',
      k4b: '-',
      k4c: '-',
      k5a: '0',
      k5b: '0',
      k5c: '-',
      k5d: '-',
      k5e: '-',
      k5f: '-',
      k5g: '-',
      k5h: '0',
      k6a: '0',
      k6b: '--',
      l1a: '-',
      l1b: '-',
      l1c: '0',
      l1d: '0',
      l1e: '0',
      l1f: '-',
      M1a: '0',
      M1b: '0',
      M1c: '0',
      M1d: '0',
      M2a: '0',
      M2b: '-',
      M3: '0',
      M4a: '0',
      M4b: '-',
      M4c: '0',
      M4d: '-',
      M4e: '-',
      M4f: '-',
      M4g: '0',
      M5a: '0',
      M5b: '0',
      M5c: '0',
      M5d: '0',
      M5e: '0',
      M5f: '0',
      M5g: '0',
      M5h: '0',
      M5i: '-',
      M6a: '-',
      M6b: '0',
      M6c: '0',
      M6d: '-',
      M6e: '-',
      M6f: '0',



    })
  }
}